version: "3.7"
networks:
  data:
    external:
      name: waisy

x-spark-common:
  &spark-common
  networks:
      - data
  volumes:
    - ./apps/jupyter:/jupyter
    - ~/data:/data
  restart: always

services:
  spark-master:
    <<: *spark-common
    container_name: spark-master
    hostname: spark-master
    image: waisy/spark-master:3.1.2-v2
    ports:
      - "9090:8080"
      - "7077:7077"
    environment:
      - "SPARK_LOCAL_IP=spark-master"

  spark-worker-1:
    <<: *spark-common
    container_name: spark-worker-1
    hostname: spark-worker-1
    image: waisy/spark-worker:3.1.2-v2
    depends_on:
      - spark-master
    ports:
      - "8081:8080"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1g
      - SPARK_DRIVER_MEMORY=128m
      - SPARK_EXECUTOR_MEMORY=1g
#      - SPARK_EXECUTOR_MEMORY=256m

  spark-worker-2:
    <<: *spark-common
    container_name: spark-worker-2
    hostname: spark-worker-2
    image: waisy/spark-worker:3.1.2-v2
    depends_on:
      - spark-master
    ports:
      - "8082:8080"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1g
      - SPARK_DRIVER_MEMORY=128m
      - SPARK_EXECUTOR_MEMORY=1g
#      - SPARK_EXECUTOR_MEMORY=256m

  jupyterlab:
    <<: *spark-common
    image: waisy/jupyterlab:3.1.2-v2
    container_name: jupyterlab
    ports:
      - "8888:8888"
