ARG BASE_IMAGE
ARG SPARK_VERSION
FROM $BASE_IMAGE

COPY spark-submit.sh /

ENV SPARK_MASTER_URL='spark://${SPARK_MASTER_HOST}:7077'
ENV SPARK_SUBMIT_ARGS=''
ENV SPARK_APPLICATION_ARGS=''
#ENV SPARK_APPLICATION_JAR_LOCATION /opt/spark-apps/myjar.jar
#ENV SPARK_APPLICATION_MAIN_CLASS my.main.Application


CMD ["/bin/bash", "/spark-submit.sh"]