ARG BASE_IMAGE
ARG SPARK_VERSION
FROM $BASE_IMAGE

COPY start-worker.sh /

ENV SPARK_WORKER_WEBUI_PORT=8080
ENV SPARK_WORKER_LOG='/spark/logs'
ENV SPARK_MASTER='spark://${SPARK_MASTER_HOST}:7077'

EXPOSE 8080

CMD ["/bin/bash", "/start-worker.sh"]